### ISSUE TITLE
Logged In users only pages

### ISSUE THREAD

**Issue by 6306** [HotPizzaYT/HxLogin#1]
How do you make a page that requires you to be logged in in order to access the page?

**Comment by HotPizzaYT** [comment]
Sorry, I've been away from GitHub for a while. Just in case you haven't learned by now (by just looking at acc.php), pages that should require you to be logged in should start and end with these codes:

Start:

```php
<?php
session_start();
if(isset($_SESSION["username"]) && isset($_SESSION["email"])){

?>
```

End:

```php

<?php
} else {
header("Location: /path/to/login/index.php");
} ?>
```
Please change the end code to the path of your login page
